services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

  # Default TranslatorInterface binding to LibreTranslate
  App\Service\TranslatorInterface: '@App\Service\Engine\LibreTranslate'

  # LibreTranslate engine
  App\Service\Engine\LibreTranslate:
    arguments:
      $apiUrl: '%env(LIBRETRANSLATE_URL)%'

  # DeepL engine
  App\Service\Engine\DeepLTranslator:
    arguments:
      $apiKey: '%env(DEEPL_API_KEY)%'
      $apiUrl: '%env(DEEPL_API_URL)%'

  # Google Translate (optional placeholder)
  App\Service\Engine\GoogleTranslator: ~

  # OpenAI GPT translator (optional)
  App\Service\Engine\OpenAiTranslator:
    arguments:
      $apiKey: '%env(OPENAI_API_KEY)%'
      $model: '%env(OPENAI_MODEL)%'

  # NLLB-Mini translator
  App\Service\Engine\NllbMiniTranslator:
    arguments:
      $endpoint: '%env(NLLB_MINI_URL)%'

  # Unified engine router
  App\Service\TranslationRouter:
    arguments:
      $libre: '@App\Service\Engine\LibreTranslate'
      $deepl: '@App\Service\Engine\DeepLTranslator'
      $nllb: '@App\Service\Engine\NllbMiniTranslator'

  # Messenger binding to avoid error
  Symfony\Component\Messenger\Command\ConsumeMessagesCommand: '@console.command.messenger_consume_messages'

  # Translation request logger middleware
  App\Middleware\TranslationLoggingMiddleware:
    tags: [messenger.middleware]

  # Monolog formatters
  monolog.formatter.json:
    class: Monolog\Formatter\JsonFormatter
    arguments:
      $batchMode: 2
      $appendNewline: true

  monolog.formatter.line:
    class: Monolog\Formatter\LineFormatter
    arguments:
      $format: "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%%\\n"
      $dateFormat: 'Y-m-d H:i:s'
