services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # LibreTranslate - default translator
    App\Service\Engine\LibreTranslate:
        arguments:
            $apiUrl: '%env(LIBRETRANSLATE_URL)%'

    App\Service\TranslatorInterface: '@App\Service\Engine\LibreTranslate'

    # Optional engines (not default)
    App\Service\Engine\OpenAiTranslator:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'
            $model: '%env(default::OPENAI_MODEL)%'

    App\Service\Engine\DeepLTranslator:
        arguments:
            $apiKey: '%env(DEEPL_API_KEY)%'
            $apiUrl: '%env(DEEPL_API_URL)%'

    App\Service\Engine\GoogleTranslator: ~

    Symfony\Component\Messenger\Command\ConsumeMessagesCommand: '@console.command.messenger_consume_messages'
