#version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - redis
      - db
    environment:
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      DATABASE_URL: mysql://symfony:symfony@db:3306/translator?serverVersion=8.0

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translator
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
