#version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: symfony_app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      APP_DEBUG: ${APP_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      LIBRETRANSLATE_URL: ${LIBRETRANSLATE_URL}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
    depends_on:
      - db
      - redis
      - libretranslate

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translator
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_API_KEY=changeme
    restart: always