#version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: symfony_app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://symfony:symfony@db:3306/translator?serverVersion=8.0
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      LIBRETRANSLATE_URL: http://libretranslate:5000
    depends_on:
      - db
      - redis
      - libretranslate

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translator
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_API_KEY=changeme
    restart: always
