doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '8.0'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true