framework:
  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      'App\Message\TranslationRequest': async

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default:
        default_middleware: true
        middleware:
          - validation
          - doctrine_transaction
          - App\Middleware\TranslationLoggingMiddleware
