monolog:
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: info
      channels: ['!event']
      formatter: monolog.formatter.json

    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine']
      formatter: monolog.formatter.line

    deprecation:
      type: stream
      path: '%kernel.logs_dir%/deprecations.log'
      level: notice
      formatter: monolog.formatter.line
