nelmio_api_doc:
  documentation:
    info:
      title: 'SaaS Translator API Gateway'
      description: 'Unified Translation API supporting multiple engines (LibreTranslate, NLLB, DeepL, OpenAI)'
      version: '1.0.0'
  areas:
    default:
      path_patterns: [ ^/api ]
