<?php

namespace ContainerFcDaAX1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_PJ30g3zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.pJ30g3z' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Message/Handler/TranslationRequestHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TranslatorFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TranslatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Engine/LibreTranslate.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Engine/GoogleTranslator.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Engine/DeepLTranslator.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Engine/OpenAiTranslator.php';

        $a = ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'));

        return $container->privates['.messenger.handler_descriptor.pJ30g3z'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Message\Handler\TranslationRequestHandler(new \App\Service\TranslatorFactory(new \App\Service\Engine\LibreTranslate($a, $container->getEnv('LIBRETRANSLATE_URL')), new \App\Service\Engine\GoogleTranslator($a), new \App\Service\Engine\DeepLTranslator($a, $container->getEnv('DEEPL_API_KEY'), $container->getEnv('DEEPL_API_URL')), new \App\Service\Engine\OpenAiTranslator($a, $container->getEnv('OPENAI_API_KEY'), $container->getEnv('OPENAI_MODEL')))), []);
    }
}
