<?php

namespace ContainerFcDaAX1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsumeTranslationsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ConsumeTranslationsCommand' shared autowired service.
     *
     * @return \App\Command\ConsumeTranslationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ConsumeTranslationsCommand.php';

        $container->privates['App\\Command\\ConsumeTranslationsCommand'] = $instance = new \App\Command\ConsumeTranslationsCommand(($container->privates['console.command.messenger_consume_messages'] ?? $container->load('getConsole_Command_MessengerConsumeMessagesService')));

        $instance->setName('app:consume-translations');

        return $instance;
    }
}
