<?php

namespace ContainerFcDaAX1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslationLoggingMiddlewareService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Middleware\TranslationLoggingMiddleware' shared autowired service.
     *
     * @return \App\Middleware\TranslationLoggingMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Middleware/TranslationLoggingMiddleware.php';

        return $container->privates['App\\Middleware\\TranslationLoggingMiddleware'] = new \App\Middleware\TranslationLoggingMiddleware(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
