<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOJXMvlx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOJXMvlx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOJXMvlx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOJXMvlx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOJXMvlx\App_KernelDevDebugContainer([
    'container.build_hash' => 'OJXMvlx',
    'container.build_id' => '1712bfde',
    'container.build_time' => 1750713504,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOJXMvlx');
