<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLC9NjJC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLC9NjJC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLC9NjJC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLC9NjJC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLC9NjJC\App_KernelDevDebugContainer([
    'container.build_hash' => 'LC9NjJC',
    'container.build_id' => '398971c5',
    'container.build_time' => 1750770733,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLC9NjJC');
