<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_translate' => [[], ['_controller' => 'App\\Controller\\Api\\TranslationController::translate'], [], [['text', '/api/translate']], [], [], []],
    'App\Controller\Api\TranslationController::translate' => [[], ['_controller' => 'App\\Controller\\Api\\TranslationController::translate'], [], [['text', '/api/translate']], [], [], []],
];
