<?php

namespace ContainerXiADyYr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HDlIiINService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HDlIiIN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HDlIiIN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5', 'get_ServiceLocator_ZHyJIs5Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5', 'get_ServiceLocator_ZHyJIs5Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5', 'get_ServiceLocator_ZHyJIs5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5', 'get_ServiceLocator_ZHyJIs5Service', true],
            'App\\Controller\\Api\\TranslationController::translate' => ['privates', '.service_locator.kbyEuPk', 'get_ServiceLocator_KbyEuPkService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5', 'get_ServiceLocator_ZHyJIs5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5', 'get_ServiceLocator_ZHyJIs5Service', true],
            'App\\Controller\\Api\\TranslationController:translate' => ['privates', '.service_locator.kbyEuPk', 'get_ServiceLocator_KbyEuPkService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Api\\TranslationController::translate' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Api\\TranslationController:translate' => '?',
        ]);
    }
}
