<?php

namespace ContainerOJXMvlx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_PJ30g3zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.pJ30g3z' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Message/Handler/TranslationRequestHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TranslatorFactory.php';

        return $container->privates['.messenger.handler_descriptor.pJ30g3z'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Message\Handler\TranslationRequestHandler(new \App\Service\TranslatorFactory()), []);
    }
}
