<?php

namespace ContainerLC9NjJC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KbyEuPkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kbyEuPk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kbyEuPk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'bus' => '?',
        ]);
    }
}
